Feature: 여신 이력 html, css 완료 및 js 일부
hanaro-ERP/hanaro-ERP-JSP pull request #11
Opened 2023-06-14 08:11 UTC by ykpark3

### 코드 작성 이유
여신 이력 페이지 html, css 완성
<br>

### 상세 사항
1. 월 선택에 따라 일 범위 변경
2. li 클릭 시 선택 및 해제 처리
3. 월 선택 시 '직접 입력' li로 선택 변경
<br>

### 참고 사항
1. 민재님 테이블 pull 받아 작업할 예정
2. 연, 일 선택 시에도 li 값 선택 변경하도록 할 예정
<br>

#### CheckList

- [ ] 웹표준 준수
- [ ] 코딩 컨벤션 준수
- [ ] 커밋 컨벤션 준수

2023-06-14 08:22 UTC, baek0402 reviewed
줄이랑 탭간격, 주석 지우기 등 통일해야 할거같습니다
일단 중간정도까지 리뷰는 했는데 그냥 상준님의 교육을 한번 다같이 듣고 추가수정 하면 될거같습니다 ㅎㅎ

2023-06-14 08:22 UTC, baek0402 commented on src/main/java/Controller/LoanContractController.java
> +	private static final long serialVersionUID = 1L;
탭 간격 확인해주세요 !

2023-06-14 08:22 UTC, baek0402 commented on src/main/java/DAO/LoanContractDAO.java
> +	private Connection conn; //DB 커넥션 연결 객체
여기도 탭간격 확인해주세요!

2023-06-14 08:22 UTC, baek0402 commented on src/main/webapp/view/loanContract/loanContract.css
> +
css 태그 사이 공백 없이 맞춰주세요 
}
.loanContract

2023-06-14 08:22 UTC, baek0402 commented on src/main/webapp/view/loanContract/loanContract.css
> +
이부분도..ㅎㅎ

2023-06-14 08:22 UTC, baek0402 commented on src/main/webapp/view/loanContract/loanContract.js
> +// selectItems 함수 호출
주석은 지워주세요 !

2023-06-14 08:22 UTC, baek0402 commented on src/main/webapp/view/loanContract/loanContract.js
> +
줄 간격이 두칸입니다 !

2023-06-14 08:49 UTC, baek0402 approved these changes
👍

2023-06-14 17:30 UTC, lake041 requested changes, later dismissed
대출일, 만기일의 직접입력 함수와 selectItems() 함수가 정상적으로 동작하지 않습니다.

2023-06-15 00:23 UTC, oxboxx commented on src/main/webapp/view/loanContract/loanContract.js
> +	});
연도 설정은 최초 1회만 실행되므로 불필요한 코드로 보입니다.

2023-06-15 00:23 UTC, oxboxx commented on src/main/webapp/view/loanContract/loanContract.js
> +	});
월 설정은 최초 1회만 실행되므로 불필요한 코드로 보입니다.

2023-06-15 00:23 UTC, oxboxx commented on src/main/webapp/view/loanContract/loanContract.js
> +			break;
모든 연도의 2월이 29일로 설정되는 오류가 있습니다.
swithc-case 대신 endDay를 new Date(연도, 월, 0).getDate()로 설정하면 연도 및 월별 일의 범위를 구할 수 있습니다.
setDaySelect() 함수의 파라미터로 선택된 연도와 월을 받도록 수정해야 될 것 같습니다.

2023-06-15 00:23 UTC, oxboxx commented on src/main/webapp/view/loanContract/loanContract.js
> +  	const monthSelect = document.getElementsByClassName("monthSelect");
대출일의 월을 변경하면 만기일의 일 범위까지 변경되는 오류가 있습니다.
이건 id 잡아서 대출일과 만기일을 따로 적용하면 될 것 같고, 일단 이 오류를 무시하면,
```
setYearSelect();
setMonthSelect();
const yearSelect = document.querySelector(".yearSelect");
const monthSelect = document.querySelector(".monthSelect");
setDaySelect(yearSelect.value, monthSelect.value);

yearSelect.addEventListener("change", () => {
	setDaySelect(yearSelect.value, monthSelect.value);	
});
monthSelect.addEventListener("change", () => {
	setDaySelect(yearSelect.value, monthSelect.value);	
});
```
이런 식으로 쓰면 될 것 같습니다.

```
endDay = new Date(parseInt(yearSelect), parseInt(monthSelect), 0).getDate();
```
setDaySelect() 함수의 endDay는 이렇게 잡았습니다.

2023-06-15 00:23 UTC, oxboxx commented on src/main/webapp/view/loanContract/loanContract.js
> +				previousListItem = item;
previousListItem이 무조건 firstListItem으로 설정되어 "전체"를 선택해도 'selectedLi'가 부여되지 않는 오류가 있습니다.
또 "전체"를 선택했을 때 나머지는 'selectedLi'가 해제되는 기능이 추가로 필요합니다.

2023-06-15 00:23 UTC, oxboxx commented on src/main/webapp/view/loanContract/loanContact.jsp
> +								<span><input id="startBalance"> 만원 이상</span>
"직접입력"과 "~만원 이상 ~만원 이하"가 별개의 요소로서 'selectedLi'가 부여되는 오류가 있습니다.

2023-06-15 00:23 UTC, oxboxx commented on src/main/webapp/view/loanContract/loanContract.js
> +function changeDateRowSelect(monthSelectId) {
"직접입력"이 디폴트로 선택되고 "전체"는 선택되지 않는 오류가 있습니다.

2023-06-15 01:11 UTC, baek0402 commented on src/main/webapp/view/loanContract/loanContract.js
> +  	const monthSelect = document.getElementsByClassName("monthSelect");
👍

2023-06-16 14:38 UTC, ykpark3 commented
1. 민재님 테이블(searchLayout?) 적용이 안 되어서 css가 약간 깨집니다.
2. DB 연동, 아래 상세테이블 구현 예정
3. 선택한 항목만 select 박스 작동하도록 수정 예정

2023-06-17 07:03 UTC, ssangjun commented on src/main/webapp/view/loanContract/loanContract.css
> +
안녕하시렵니까, 개행이라고합니다

2023-06-17 07:05 UTC, ssangjun commented on src/main/java/Bean/LoanContract.java
> +    int lc_id, l_id, c_id, e_id;
여기 들여쓰기가 스페이스바 인 것 같습니다

2023-06-17 07:05 UTC, ssangjun commented on src/main/java/Controller/LoanContractController.java
> +    public LoanContractController() {
여기도 들여쓰기가 스페이스바 인 것 같습니다.

2023-06-17 07:10 UTC, ssangjun reviewed
전체적으로 들여쓰기가 탭인지 스페이스바인지 확인 부탁드리고
develop 브랜치 최신화 하셔서 작업 브랜치에 머지시키셔서 최신화 한 번 부탁드립니다.

탭인지 스페이스바인지는 이클립스보다 깃헙 Files changed 보시면 쉽게 식별 가능합니다.
깃 관련해서는 언제든지 여쭤봐주세요!

2023-06-19 00:43 UTC, ssangjun approved these changes
고생하셨씁니다~~ 👍👍👍

2023-06-19 01:41 UTC, merged